### ISSUE TITLE
[Bug] Constant Re-Hosting causes items to clip on inside the ship

### ISSUE THREAD

**Issue by broken-usb** [mattymatty97/LTC_MattyFixes#23]
Hi, it's me again.

**Describe the bug**
If you keep entering and leaving a save file items will slowly clip inside of the ship until they cant be seen anymore (they still count as inside the ship tho, as seen with mods like ShipLoot).

**To Reproduce**
Profile code: `01910a3f-a549-ec8b-9e30-288ccff9383f`
1. Play the game normally and accumulate some decent scrap inside your ship
2. Wait for the game to save or force it to save with LobbyControl
3. Leave the lobby
4. Enter the same save file
5. Repeat steps 3 and 4 and you will notice your items slowly going into the floor

**Expected behavior**
Items shouldn't clip into the floor.

**Screenshots**

**Versions:**
 - Game: v55/56
 - Mod: v1.1.14
 - Experimental: yes

**Logs**
[LogOutput.log](https://github.com/user-attachments/files/16446240/LogOutput.log)

**Additional context**
I think this started happening when v1.1.12 got release although it wasn't this consistent at the time, here are some clips of me showing the problem:

https://github.com/user-attachments/assets/d0939025-8f97-4fcf-b36e-dd65559d59a1

https://github.com/user-attachments/assets/f3c3326f-2f05-4a83-97a1-312bf48c0d46

https://github.com/user-attachments/assets/522bdd64-4f30-4f6a-bc6f-15cbf5eba7b0

In the last one you can also see some previous clipped items appearing back but it doesn't takes much time before they start to clip again. This bug also affects items that you place **on top** of the Cupboard, said items will fall down into the cupboard.
Doesn't just happen with the smaller scrap, two-handed items also get affect by it but the Fancy Lamps seem to be immune to it for some reason.

**Comment by broken-usb** [comment]
I've seen that a similar issue got reported before and yes, i have GeneralImprovements and yes, all of its fixes are turned off (except the sell counter change)
![image](https://github.com/user-attachments/assets/eaf051b7-0be2-4537-9b71-7abb2aa79b1e)

Both compatibility settings are also turned off (although turning them on doesn't solve the issue)
![image](https://github.com/user-attachments/assets/0271db0b-5d5e-4269-a075-f5653ec61b69)
![image](https://github.com/user-attachments/assets/aacf9cc0-f5ab-4370-b026-a946b0c6b578)

**Comment by mattymatty97** [comment]
the new experimental should fix this issue, please make sure OutOfBouns.VerticalOffset is non-zero

**Comment by NakiriFox** [comment]
Ask a question unrelated to this issue :)

When will MattyFixesExperimental and LobbyControlExperimental be merged into the official version?

**Comment by mattymatty97** [comment]
the answer to that is simply "when i am sure they are stable and w/o issues"

**Comment by broken-usb** [comment]
Also, adding more on this, i have some items that got stuck under the Ship due to this bug and the OutOfBounds check seems to still consider them as properly inside of the ship(Increasing the Vertical Offset of the OutOfBounds config also doesn't solve it):
![1966720_20240802165540_1](https://github.com/user-attachments/assets/425e5642-2ae6-4912-876e-8f57f2daaa06)
You can only see a few items under there on the Screenshot but there is around 1k - 2k scrap value lying under there which is pretty annoying.
Maybe adding a way to forcefully teleport all items into the middle of the Ship could help solve this?

**Comment by broken-usb** [comment]
Suddendly the items got teleported back inside the Ship, closing the issue as it seems to be fixed
